name: SonarCloud Scan

on:
  workflow_dispatch:

jobs:
  Sonarcloud-Scan:
    name: SonarCloud.Scan
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16' # Specify the Node.js version you are using

      - name: Install dependencies
        run: npm install
      
      - name: Install SonarScanner
        run: |
          npm install -g sonarqube-scanner
      
      - name: SonarCloud Scan
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        run: |
          sonar-scanner \
            -Dsonar.projectKey=BhanuPrakash0710_PackYourBags\
            -Dsonar.organization=bhanuprakash0710 \
            -Dsonar.tags= vroom \
            -Dsonar.login=${{ secrets.SONAR_TOKEN }} 

      - name: Upload SonarCloud results (if using npm scripts)
        run: npm run sonar
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
